# fly.toml app configuration file generated for young-sun-3545 on 2023-08-04T18:20:19+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "young-sun-3545"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
